### ISSUE TITLE
CHANNEL ？

### ISSUE THREAD

**Issue by xiangdeyizhang** [AbnerHqC/GaitSet#10]
你好，打扰了，我现在预处理已经做好了，但是在我运行的时候，一直提示    return getattr(obj, method)(*args, **kwds)
AttributeError: 'NoneType' object has no attribute 'reshape' 关于reshape的问题。
我定位的错误应该是
        frame_list = [np.reshape(
            cv2.imread(osp.join(flie_path, _img_path)),
            [self.resolution, self.resolution, -1])[:, :, 0]
                      for _img_path in imgs
                      if osp.isfile(osp.join(flie_path, _img_path))]
是这句话，这个是因为通道数的问题吗，我预处理后保存的图像是灰度图，但是cv2.imread读取后不是会自动转换为3通道吗，谢谢，期待你的回复

**Comment by AbnerHqC** [comment]
你确定的路径正确么？看起来像是imread返回了None
