### ISSUE TITLE
execute pretreatment error!!!

### ISSUE THREAD

**Issue by viekie** [AbnerHqC/GaitSet#12]
first: I unzip datasetb and put dataset at dir '/root/DatasetB/silhouettes' like folder 001 002 003 and so on, 
second: I run  python3 pretreatment.py --input_path='/root/DatasetB/silhouettes/' --output_path='/root/DatasetB/output/',then i got the following warning. And no data generated !
JOB 440 : --WARNING-- seq:005-bg-01-000, less than 5 valid data.
JOB 448 : --WARNING-- seq:005-bg-01-144, frame:005-bg-01-144-061.png, no data, 0.
JOB 448 : --WARNING-- seq:005-bg-01-144, frame:005-bg-01-144-062.png, no data, 0.
JOB 448 : --WARNING-- seq:005-bg-01-144, frame:005-bg-01-144-063.png, no data, 0.
JOB 448 : --WARNING-- seq:005-bg-01-144, frame:005-bg-01-144-064.png, no data, 0.
JOB 448 : --WARNING-- seq:005-bg-01-144, frame:005-bg-01-144-065.png, no data, 0.
JOB 449 : --WARNING-- seq:005-bg-01-162, frame:005-bg-01-162-001.png, no data, 0.
JOB 449 : --WARNING-- seq:005-bg-01-162, frame:005-bg-01-162-002.png, no data, 0.

**Comment by AbnerHqC** [comment]
Hi, the warning is normal. Some samples in the dataset is highly noisy and the pretreatment will skip these samples.
