### ISSUE TITLE
OU-MVLP  identical-view 

### ISSUE THREAD

**Issue by SigmaLGX** [AbnerHqC/GaitSet#13]
你好，AbnerHqC
       非常感谢你提供开源代码，我在CASIA-B数据集上，成功复现了README中的rank@1。但是，在CASIA-B数据集上面训练的模型，在OU-MVLP上的rank@1很低，rank1=45.01%。
         我想咨询下，在README中记录的OU-MVLP数据集上 Rank@1=87.1%，是使用CASIA-B数据集训练的还是OU-MVLP数据集训练的？

**Comment by AbnerHqC** [comment]
需要重新训练的。因为OU比CASIA大太多了，batch_size和各层的channel数也需要调大一些。具体设置可以看我们论文中4.1节/Training Details。

**Comment by SigmaLGX** [comment]
好的，谢谢。 已经成功复现了！

**Comment by AbnerHqC** [comment]
不客气～

**Comment by 853498747** [comment]
你好，请问复现OU-MVLP的话，dataloader是要自己重写吗？

**Comment by panv11** [comment]
请问如何获取OU-MVLP或者OU-ISIR数据集
