### ISSUE TITLE
Extracting human contours

### ISSUE THREAD

**Issue by tangbinbinyes** [AbnerHqC/GaitSet#14]
Hello, if my dataset, the background in the video screen changes, is not stable, can I extract the human contour map very well? For example, there are other pedestrians and vehicles behind the pedestrians. I think it should have an impact, and the impact is still relatively large. That is to say, if there are other moving objects in the picture, the human contour cannot be extracted.

**Comment by AbnerHqC** [comment]
Yes, this could be a problem in practical scenarios. You might need to find a good segmentation algorithm.
