### ISSUE TITLE
运行train.py文件时，随机取样有问题，请问怎么解决？

### ISSUE THREAD

**Issue by Lookformyuniverse** [AbnerHqC/GaitSet#158]
![image](https://user-images.githubusercontent.com/96779839/177706749-ff5ac735-7351-49f4-a920-28a92e3de40a.png)
具体报错如图，不知道是哪里超过取样范围了？

**Comment by Tqhuyen** [comment]
problem solved here: https://github.com/AbnerHqC/GaitSet/issues/26

**Comment by Lookformyuniverse** [comment]
> 

Thank you!
