### ISSUE TITLE
Unexpected Results for 24-subject training on CASIA-B.

### ISSUE THREAD

**Issue by dongb5** [AbnerHqC/GaitSet#16]
Hi,
I recently ran your code on CASIA-B dataset to replicate the experiments. However, I had trouble in achieving the results reported in the paper. Below is the results I got:
```
Loading the model of iteration 80000...
Transforming...
Evaluating...
Evaluation complete. Cost: 1:12:31.519665
===Rank-1 (Include identical-view cases)===
NM: 10.178,     BG: 5.941,      CL: 3.517
===Rank-1 (Exclude identical-view cases)===
NM: 5.810,      BG: 4.069,      CL: 2.557
===Rank-1 of each angle (Exclude identical-view cases)===
NM: [6.16 5.61 7.12 4.85 6.11 6.92 5.96 5.56 6.42 5.26 3.94]
BG: [3.79 4.24 4.60 3.67 5.00 4.85 3.94 3.45 3.60 3.64 3.96]
CL: [1.62 2.78 2.48 3.20 3.03 3.24 2.98 2.49 2.49 2.26 1.57]
```

The training outputs are like these:
```
iter 74000:, hard_loss_metric=0.20000003, full_loss_metric=0.20000003, full_loss_num=229376.00000000, mean_dist=0.00000000, lr=0.000100, hard or full='hard'
0:03:51.626398
iter 75000:, hard_loss_metric=0.20000003, full_loss_metric=0.20000003, full_loss_num=229376.00000000, mean_dist=0.00000000, lr=0.000100, hard or full='hard'
0:03:51.586907
iter 76000:, hard_loss_metric=0.20000003, full_loss_metric=0.20000003, full_loss_num=229376.00000000, mean_dist=0.00000000, lr=0.000100, hard or full='hard'
0:03:51.859781
iter 77000:, hard_loss_metric=0.20000003, full_loss_metric=0.20000003, full_loss_num=229376.00000000, mean_dist=0.00000000, lr=0.000100, hard or full='hard'
0:03:46.837857
iter 78000:, hard_loss_metric=0.20000003, full_loss_metric=0.20000003, full_loss_num=229376.00000000, mean_dist=0.00000000, lr=0.000100, hard or full='hard'
0:03:46.709837
iter 79000:, hard_loss_metric=0.20000003, full_loss_metric=0.20000003, full_loss_num=229376.00000000, mean_dist=0.00000000, lr=0.000100, hard or full='hard'
0:03:49.217351
iter 80000:, hard_loss_metric=0.20000003, full_loss_metric=0.20000003, full_loss_num=229376.00000000, mean_dist=0.00000000, lr=0.000100, hard or full='hard'
Training COMPLETE
```
The triplet losses were 0.20000003 from about 10000th iteration and kept same till the end of training.
I have also tried to stop at 10000th iteration, but I got similar results as above.
Due to computational resources, I have not ran the 62-subject and 73-subject experiments.

I have ran the pretreatment.py following the instruction, and it worked well, only gave some warnings.
I have not modified the config.py, except for the 'pid_num' and paths.
I also modified the `random.choices` to `np.random.choice`, because the former one is a new feature in Python 3.6, while I used 3.5. 
I have not modified other codes. Can you give any help? Thanks.

**Comment by LGCLT** [comment]
Is there a good moving target detection algorithm code?

**Comment by AbnerHqC** [comment]
There might be some fatal mistakes in your dataset. Have you pretreated the dataset following the guidance in _readme_ ? The original data needs to be cut and resized.

**Comment by AbnerHqC** [comment]
@LGCLT Sorry, we didn't include any detection or tracking algorithms in this project.

**Comment by dongb5** [comment]
@AbnerHqC As I said, I have ran the pretreatment.py and the images were cropped into 64x64.

**Comment by dongb5** [comment]
By the way, the dataset should be right. All the researches in my lab are based on the same dataset source.

**Comment by AbnerHqC** [comment]
@dongb5 Sorry, I saw your issue on my cell-phone yesterday and missed the full description. It seems you changed the triplet loss into 'hard' mode (`'hard_or_full_trip'` in the `config.py` whose default value is  `'full'`). The hard triplet loss could easily collapse in the training so unless the model is improved, you should not change this setting field. Actually, I'm considering to remove the hard triplet loss from the code.

**Comment by dongb5** [comment]
Thanks. The codes have ran well using 'full' triplet loss.

**Comment by aldotripolyta** [comment]
@dongb5 hey, could you help me with this error on test.py? Thank you.

(base) D:\Road.to.Sidang\Python\GaitRecog\Master2>python test.py
Initialzing...
Initializing data source...
Data initialization complete.
Initializing model...
Model initialization complete.
Loading the model of iteration 10000...
Transforming...
Evaluating...
Traceback (most recent call last):
  File "test.py", line 44, in <module>
    acc = evaluation(test, conf['data'])
  File "D:\Road.to.Sidang\Python\GaitRecog\Master2\model\utils\evaluator.py", line 47, in evaluation
    0) * 100 / dist.shape[0], 2)
ValueError: could not broadcast input array from shape (4) into shape (5)

**Comment by dongb5** [comment]
@aldotripolyta You may want to print the shapes of arrays used in this line of codes to see if there is any unmatched shape. You can also open a new issue to ask for the help of the author.
