### ISSUE TITLE
应用推广限制

### ISSUE THREAD

**Issue by SigmaLGX** [AbnerHqC/GaitSet#19]
你好，AbnerHqC
        我在CASIA-B以及OU数据集上，复现了你们的成果，取得了很好的行人识别率。但是，在实际场景中，我们很难取得比较号的行人轮廓图片。 
        不知道你们有没有考虑，从RGB彩色图片中获取步态信息，而不是从黑白轮廓图中获取？

**Comment by AbnerHqC** [comment]
您好，您提的问题非常好。步态现在两个常用数据集casia和ou都只提供轮廓图，这实际上限制了这一方向的发展。毕竟轮廓图已经是使用了很多年的东西了。随着工业界的关注，我们其实非常期待能有更加完善的数据集能公开出来。比如能有原始视频序列，更复杂的场景，更多的人体gesture和着装变化等等。

不过最初步态使用轮廓图也不是没有原因的，它直观的解决了基于rgb图像的模型更依赖颜色和纹理的问题。使得换衣情况下的识别成为可能（reid方向的工作则恰恰相反）。

**Comment by SigmaLGX** [comment]
您好
我尝试将Market + Duke 数据集应用在GaitSet模型上。将图片从彩色图转换为灰度图片，并且每个ID的图片平均分为两个camera。（尽管数据集不是同一个camera拍摄的，并且行人的图片也不是连续的。）然后使用您提供的网络进行训练。

结果rank1有65%的准确率。 所以我猜想，假如有完整的彩色步态数据的话，GaitSet依旧能取得不错的效果。

除了CASIA以及OU数据集，您还了解其他关于步态的数据集吗？或者是连续的行人重识别数据集？

**Comment by AbnerHqC** [comment]
Reid数据集请看这里：[Person Re-identification Datasets](http://robustsystems.coe.neu.edu/sites/robustsystems.coe.neu.edu/files/systems/projectpages/reiddataset.html)~
reid数据集背景都很复杂，把人抠出来估计效果更好。
不过用灰度图的话还是不能排除纹理信息，reid数据集都不换装，大多甚至是同源的。
真实场景人要换装加上不同gesture问题应该会难很多。

**Comment by tangbinbinyes** [comment]
The CASIA-B gait dataset provides the original video, but only after downloading and signing the agreement, it will be issued after review.

**Comment by SigmaLGX** [comment]
谢谢！
