### ISSUE TITLE
live camera test

### ISSUE THREAD

**Issue by liuhengli** [AbnerHqC/GaitSet#2]
I want to know how to test on camera if very frame have many people

**Comment by AbnerHqC** [comment]
Hi，we are trying to improve the usability of our interface. But for now, you need  to use detection and segmentation methods to generate silhouettes first.

**Comment by liuhengli** [comment]
I konw need detection and segmentation methods, but if there are more than one person in the video, how can we generate everyone's silhouettes.

**Comment by AbnerHqC** [comment]
Like most of person re-id and gait recognition model, our model take silhouettes of a single person as input. I think detection could cover this problem. But the shelter between different person might cause drawback as current gait datasets are quite clean.
