### ISSUE TITLE
一个人最少要录几个视屏用于训练

### ISSUE THREAD

**Issue by tangbinbinyes** [AbnerHqC/GaitSet#21]
我今天做测试的时候，一个人只是录了一个视屏得到一份轮廓图，但是我的文件夹里面只有一份数据轮廓数据就会报错，请问这个问题我该如何解决，虽然可以复制一份相同的得到两份数据，但是这样的话太占用空间了，能不能从代码上解决

这是两份数据
![image](https://user-images.githubusercontent.com/41097044/51324242-2e496a00-1aa5-11e9-93c6-60e3ed64f2b8.png)

这是一份数据的情况，会报错，下标越界
![image](https://user-images.githubusercontent.com/41097044/51324283-47eab180-1aa5-11e9-98f0-901560cc3c86.png)

**Comment by AbnerHqC** [comment]
训练的时候一个序列显然是不满足triplet loss要求的。测试的时候至少得有两个一个probe一个gallery吧。
