### ISSUE TITLE
What exactly the dataset looks like when running test.py?

### ISSUE THREAD

**Issue by tenggyut** [AbnerHqC/GaitSet#3]
```
def __loader__(self, path):
        file_path = osp.join(path, os.listdir(path)[0])
        seq = pickle.load(open(file_path, 'rb'))
        data_type = seq.attrs['data_type']
        data_name = seq.name
        if data_name in self.selector:
            seq = seq.loc.__getitem__(tuple(self.selector[data_name]))
        if data_type == 'img':
            seq = seq.astype('float32')
            seq /= 255.0
            seq = seq[:, :, 10:54]
        return seq
```
in `data_set.py`,  what the pickle tries to load, not a image?

**Comment by AbnerHqC** [comment]
Hi, please re-pull the code. We have fixed this problem.

**Comment by AbnerHqC** [comment]
OK, a good idea. Actually, there is this parameter in the initialization function. I'll add an argument in the commend line and expose this parameter. Check the latest version in 2 hours.

**Comment by AbnerHqC** [comment]
What's more, I'm wondering if you have cut, aligned and resize the silhouette before you start the experiment. Since a 64G RAM is quite enough for CASIA-B. If I remember correctly, the entire CASIA-B would take less than 20G memory.

**Comment by tenggyut** [comment]
Hemm...the align thing is the root cause of my RAM issue... Thanks for the clarification

**Comment by AbnerHqC** [comment]
There is a bug in version 3ea76b0784a299105be2f8ce0a6525ed24446f56 which could cause a slight drawback of the performance. You might want to update to the latest version.:grinning:

**Comment by tenggyut** [comment]
OK!

I am currently trying to write codes so that I could test the model on my custom dataset which helps me to understand your work more clearly! The coding working is close to finished, but one thing is not very clear to me. the shape of the feature tensor is [1, 62, 256], 1 is the batch size, 256 is the hidden unit size, where is the 62 comes from, does it have a meaning?

**Comment by AbnerHqC** [comment]
Of cause, the HPM module will generate 1+2+4+8+16=31 features in different scales for both main pipeline and global pipeline (31+31=62). In the test phase, the 62 features will be concatenated into one 62x256=15872 feature as a final representation. For details, you can refer to our [paper](https://arxiv.org/abs/1811.06186).

**Comment by prashant-bansod** [comment]
@tenggyut I just went through the previous conversation. Could you please tell me how did you create your own dataset? Thank you.

**Comment by tenggyut** [comment]
> @tenggyut I just went through the previous conversation. Could you please tell me how did you create your own dataset? Thank you.

I 'm not quite sure what do you mean by "create your own dataset".

If you mean how I collected my own dataset, my answer is: my colleagues collected them for me
If you mean how I feed the data to the model during training, I wrote a producer-customer pipeline to do it.

**Comment by prashant-bansod** [comment]
@tenggyut  thanks for your reply. Could you please tell me how should I test this code on some other samples? I mean to say how to check the accuracies on the new set of data. Suppose I take some samples from CASIA dataset and I want to test the accuracies. Where should I make changes to see the results. Do I have to change the `config.py` or I have to do something with the  `probe_seq_dict` or `gallery_seq_dict` ? Please pardon me if my understanding is horribly wrong.  I just want to test the accuracies.
I tried to understand the probe and gallery samples from some other papers. This is what I  found
`the probe subject is matched to all gallery subjects in the database and a list of candidates with highest posterior probabilities is the output in the descending order`

I would appreciate your advice on this.Thank you .

**Comment by prashant-bansod** [comment]
> OK!
> 
> I am currently trying to write codes so that I could test the model on my custom dataset which helps me to understand your work more clearly! The coding working is close to finished, but one thing is not very clear to me. the shape of the feature tensor is [1, 62, 256], 1 is the batch size, 256 is the hidden unit size, where is the 62 comes from, does it have a meaning?

@tenggyut I am also trying to test the model on my dataset. The evaluation `function `seems to be very hard to understand. Could you please give share some insights from your custom code which evaluates the performance of the model on the new test images?  Do I have to create my own dataset in the same way as it is in the CASIA?

**Comment by tenggyut** [comment]
I fully customized the evaluation code....

my evaluate the two task: identification(1:N) and verification (1:1). use the trained model to get gaits embeddings and calculate the distance of embeddings, then you can calculate metrics based on the distances and thresholds you choose...

**Comment by dayday2019** [comment]
> > OK!
> > I am currently trying to write codes so that I could test the model on my custom dataset which helps me to understand your work more clearly! The coding working is close to finished, but one thing is not very clear to me. the shape of the feature tensor is [1, 62, 256], 1 is the batch size, 256 is the hidden unit size, where is the 62 comes from, does it have a meaning?
> 
> @tenggyut I am also trying to test the model on my dataset. The`evaluation`function seems to be very hard to understand. Could you please give share some insights from your custom code which evaluates the performance of the model on the new test images? Do I have to create my own dataset in the same way as it is in the CASIA?
> Thanks

こんにちは。I have the same problem just like this,could you share me with your solution? Thank you!

**Comment by leon5678** [comment]
> I fully customized the evaluation code....
> 
> my evaluate the two task: identification(1:N) and verification (1:1). use the trained model to get gaits embeddings and calculate the distance of embeddings, then you can calculate metrics based on the distances and thresholds you choose...

could you please tell me that how did you choose the thresholds?

**Comment by tenggyut** [comment]
> > I fully customized the evaluation code....
> > my evaluate the two task: identification(1:N) and verification (1:1). use the trained model to get gaits embeddings and calculate the distance of embeddings, then you can calculate metrics based on the distances and thresholds you choose...
> 
> could you please tell me that how did you choose the thresholds?

you have to try various thresholds and chose the one that performs best....
