### ISSUE TITLE
What's the purpose of the resolution parameter?

### ISSUE THREAD

**Issue by ZhangYuef** [AbnerHqC/GaitSet#30]
I found that in `data_set.py` you tend to cut the image according to resolution setting.

`self.img2xarray(
            path)[:, :, self.cut_padding:-self.cut_padding].astype(
            'float32') / 255.0`

Why should we use this operation to cut the raw `64x64` image to `44*64` one?

**Comment by AbnerHqC** [comment]
To save the GPU memory. It's almost certain that in two sides of a silhouette all pixels are black.
