### ISSUE TITLE
关于sp

### ISSUE THREAD

**Issue by Cyprusky** [AbnerHqC/GaitSet#37]
您好，如果我想要修改sp相关内容，应该注意哪些代码呢？十分感谢您的帮助

**Comment by AbnerHqC** [comment]
您好，抱歉才回复您。修改SP的话需要注意批量测试的代码，相关代码有gaitset中batch_frame相关部分和model中collate_fn()相关部分。主要是一批样本中各个样本长度不同如何组成batch的问题。目前的解决方案比较拍脑门，不可通用

**Comment by Cyprusky** [comment]
> 您好，抱歉才回复您。修改SP的话需要注意批量测试的代码，相关代码有gaitset中batch_frame相关部分和模型中collat​​e_fn（）相关部分。主要是一批样本中各个样本长度不同如何组成批次的问题。目前的解决方案比较拍脑门，不可通用

感谢您百忙之中回复我的问题，十分感谢
