### ISSUE TITLE
set-level feature  and set-level feature

### ISSUE THREAD

**Issue by Cyprusky** [AbnerHqC/GaitSet#40]
您好，请问set-level feature 和set-level feature应该怎么理解呢？？十分需要您的帮助。谢谢

**Comment by AbnerHqC** [comment]
您好，论文中Frame level是指单帧提取出的信息。set level是指整个set的特征。

**Comment by Cyprusky** [comment]
> 您好，论文中Frame level是指单帧提取出的信息。set level是指整个set的特征。

您好，看了您的论文，您说的sp操作不同带来算法的性能也不同，那么在代码中哪一部分是sp操作部分，恳请您指点。

**Comment by ZiYueZH** [comment]
sp操作在单个frame的共享cnn处理之后吧，frame_max和HPP，hpm等部分都是针对set的操作吧。模型代码在gaitset,py里面，在forward函数里面可以看到整个流程，包括multiple pipeline等操作。

**Comment by Cyprusky** [comment]
> sp操作在单个frame的共享cnn处理之后吧，frame_max和HPP，hpm等部分都是针对set的操作吧。模型代码在gaitset,py里面，在forward函数里面可以看到整个流程，包括multiple pipeline等操作
