### ISSUE TITLE
 FileNotFoundError: [WinError 2] The system cannot find the file specified: './work' in train.py 

### ISSUE THREAD

**Issue by atppb** [AbnerHqC/GaitSet#42]

**Comment by Cyprusky** [comment]
I think you can change your WORK_PATH to D:/Road.to.Sidang/Python/GaitRecog/Master/work.
It may be work.;)

**Comment by Cyprusky** [comment]
> (base) D:\Road.to.Sidang\Python\GaitRecog\Master>python train.py --cache=false
> Initialzing...
> Initializing data source...
> Data initialization complete.
> Initializing model...
> Model initialization complete.
> Training START
> THCudaCheck FAIL file=c:\a\w\1\s\tmp_conda_3.6_090826\conda\conda-bld\pytorch_1550394668685\work\torch\csrc\generic\StorageSharing.cpp line=232 error=71 : operation not supported
> Traceback (most recent call last):
> File "train.py", line 21, in 
> m.fit()
> File "D:\Road.to.Sidang\Python\GaitRecog\Master\model\model.py", line 150, in fit
> for seq, view, seq_type, label, batch_frame in train_loader:
> File "C:\Users\TRIPOLYTA\Anaconda3\lib\site-packages\torch\utils\data\dataloader.py", line 819, in **iter**
> return _DataLoaderIter(self)
> File "C:\Users\TRIPOLYTA\Anaconda3\lib\site-packages\torch\utils\data\dataloader.py", line 560, in **init**
> w.start()
> File "C:\Users\TRIPOLYTA\Anaconda3\lib\multiprocessing\process.py", line 105, in start
> self._popen = self._Popen(self)
> File "C:\Users\TRIPOLYTA\Anaconda3\lib\multiprocessing\context.py", line 223, in _Popen
> return _default_context.get_context().Process._Popen(process_obj)
> File "C:\Users\TRIPOLYTA\Anaconda3\lib\multiprocessing\context.py", line 322, in _Popen
> return Popen(process_obj)
> File "C:\Users\TRIPOLYTA\Anaconda3\lib\multiprocessing\popen_spawn_win32.py", line 65, in **init**
> reduction.dump(process_obj, to_child)
> File "C:\Users\TRIPOLYTA\Anaconda3\lib\multiprocessing\reduction.py", line 60, in dump
> ForkingPickler(file, protocol).dump(obj)
> File "C:\Users\TRIPOLYTA\Anaconda3\lib\site-packages\torch\multiprocessing\reductions.py", line 213, in reduce_tensor
> (device, handle, storage_size_bytes, storage_offset_bytes) = storage._share_cuda_()
> RuntimeError: cuda runtime error (71) : operation not supported at c:\a\w\1\s\tmp_conda_3.6_090826\conda\conda-bld\pytorch_1550394668685\work\torch\csrc\generic\StorageSharing.cpp:232
> 
> (base) D:\Road.to.Sidang\Python\GaitRecog\Master>Initialzing...
> Traceback (most recent call last):
> File "", line 1, in 
> File "C:\Users\TRIPOLYTA\Anaconda3\lib\multiprocessing\spawn.py", line 105, in spawn_main
> exitcode = _main(fd)
> File "C:\Users\TRIPOLYTA\Anaconda3\lib\multiprocessing\spawn.py", line 114, in _main
> prepare(preparation_data)
> File "C:\Users\TRIPOLYTA\Anaconda3\lib\multiprocessing\spawn.py", line 225, in prepare
> _fixup_main_from_path(data['init_main_from_path'])
> File "C:\Users\TRIPOLYTA\Anaconda3\lib\multiprocessing\spawn.py", line 277, in _fixup_main_from_path
> run_name="**mp_main**")
> File "C:\Users\TRIPOLYTA\Anaconda3\lib\runpy.py", line 263, in run_path
> pkg_name=pkg_name, script_name=fname)
> File "C:\Users\TRIPOLYTA\Anaconda3\lib\runpy.py", line 96, in _run_module_code
> mod_name, mod_spec, pkg_name, script_name)
> File "C:\Users\TRIPOLYTA\Anaconda3\lib\runpy.py", line 85, in _run_code
> exec(code, run_globals)
> File "D:\Road.to.Sidang\Python\GaitRecog\Master\train.py", line 18, in 
> m = initialization(conf, train=opt.cache)[0]
> File "D:\Road.to.Sidang\Python\GaitRecog\Master\model\initialization.py", line 55, in initialization
> os.chdir(WORK_PATH)
> **FileNotFoundError: [WinError 2] The system cannot find the file specified: './work'**
> 
> my config.py
> 
> conf = {
> "WORK_PATH": "./work",
> "CUDA_VISIBLE_DEVICES": "0",
> "data": {
> 'dataset_path': "D:/Road.to.Sidang/Python/GaitRecog/Master/OutputGEI01",
> 'resolution': '64',
> 'dataset': 'CASIA-B',
> # In CASIA-B, data of subject #5 is incomplete.
> # Thus, we ignore it in training.
> # For more detail, please refer to
> # function: utils.data_loader.load_data
> 'pid_num': 73,
> 'pid_shuffle': False,
> },
> "model": {
> 'hidden_dim': 256,
> 'lr': 1e-4,
> 'hard_or_full_trip': 'full',
> 'batch_size': (8, 16),
> 'restore_iter': 0,
> 'total_iter': 80000,
> 'margin': 0.2,
> 'num_workers': 3,
> 'frame_num': 30,
> 'model_name': 'GaitSet',
> },
> 
> Can you help me please?

I think you can change your WORK_PATH to D:/Road.to.Sidang/Python/GaitRecog/Master/work.
It may be work.;)

**Comment by aldotripolyta** [comment]
@Cyprusky thank you, but I faced another problem.

(base) D:\Road.to.Sidang\Python\GaitRecog\Master>python train.py
C:\Users\TRIPOLYTA\Anaconda3\lib\site-packages\distributed\utils.py:134: RuntimeWarning: Couldn't detect a suitable IP address for reaching '8.8.8.8', defaulting to '127.0.0.1': [WinError 10065] A socket operation was attempted to an unreachable host
  % (host, default, e), RuntimeWarning)
Initialzing...
Initializing data source...
Loading training data...
Data initialization complete.
Initializing model...
Model initialization complete.
Training START
Traceback (most recent call last):
  File "train.py", line 21, in <module>
    m.fit()
  File "D:\Road.to.Sidang\Python\GaitRecog\Master\model\model.py", line 150, in fit
    for seq, view, seq_type, label, batch_frame in train_loader:
  File "C:\Users\TRIPOLYTA\Anaconda3\lib\site-packages\torch\utils\data\dataloader.py", line 819, in __iter__
    return _DataLoaderIter(self)
  File "C:\Users\TRIPOLYTA\Anaconda3\lib\site-packages\torch\utils\data\dataloader.py", line 560, in __init__
    w.start()
  File "C:\Users\TRIPOLYTA\Anaconda3\lib\multiprocessing\process.py", line 105, in start
    self._popen = self._Popen(self)
  File "C:\Users\TRIPOLYTA\Anaconda3\lib\multiprocessing\context.py", line 223, in _Popen
    return _default_context.get_context().Process._Popen(process_obj)
  File "C:\Users\TRIPOLYTA\Anaconda3\lib\multiprocessing\context.py", line 322, in _Popen
    return Popen(process_obj)
  File "C:\Users\TRIPOLYTA\Anaconda3\lib\multiprocessing\popen_spawn_win32.py", line 65, in __init__
    reduction.dump(process_obj, to_child)
  File "C:\Users\TRIPOLYTA\Anaconda3\lib\multiprocessing\reduction.py", line 60, in dump
    ForkingPickler(file, protocol).dump(obj)
MemoryError
C:\Users\TRIPOLYTA\Anaconda3\lib\site-packages\distributed\utils.py:134: RuntimeWarning: Couldn't detect a suitable IP address for reaching '8.8.8.8', defaulting to '127.0.0.1': [WinError 10065] A socket operation was attempted to an unreachable host
  % (host, default, e), RuntimeWarning)

(base) D:\Road.to.Sidang\Python\GaitRecog\Master>Initialzing...
Initializing data source...
Loading training data...
Data initialization complete.
Initializing model...
Model initialization complete.
Training START
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "C:\Users\TRIPOLYTA\Anaconda3\lib\multiprocessing\spawn.py", line 105, in spawn_main
    exitcode = _main(fd)
  File "C:\Users\TRIPOLYTA\Anaconda3\lib\multiprocessing\spawn.py", line 114, in _main
    prepare(preparation_data)
  File "C:\Users\TRIPOLYTA\Anaconda3\lib\multiprocessing\spawn.py", line 225, in prepare
    _fixup_main_from_path(data['init_main_from_path'])
  File "C:\Users\TRIPOLYTA\Anaconda3\lib\multiprocessing\spawn.py", line 277, in _fixup_main_from_path
    run_name="__mp_main__")
  File "C:\Users\TRIPOLYTA\Anaconda3\lib\runpy.py", line 263, in run_path
    pkg_name=pkg_name, script_name=fname)
  File "C:\Users\TRIPOLYTA\Anaconda3\lib\runpy.py", line 96, in _run_module_code
    mod_name, mod_spec, pkg_name, script_name)
  File "C:\Users\TRIPOLYTA\Anaconda3\lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "D:\Road.to.Sidang\Python\GaitRecog\Master\train.py", line 21, in <module>
    m.fit()
  File "D:\Road.to.Sidang\Python\GaitRecog\Master\model\model.py", line 150, in fit
    for seq, view, seq_type, label, batch_frame in train_loader:
  File "C:\Users\TRIPOLYTA\Anaconda3\lib\site-packages\torch\utils\data\dataloader.py", line 819, in __iter__
    return _DataLoaderIter(self)
  File "C:\Users\TRIPOLYTA\Anaconda3\lib\site-packages\torch\utils\data\dataloader.py", line 560, in __init__
    w.start()
  File "C:\Users\TRIPOLYTA\Anaconda3\lib\multiprocessing\process.py", line 105, in start
    self._popen = self._Popen(self)
  File "C:\Users\TRIPOLYTA\Anaconda3\lib\multiprocessing\context.py", line 223, in _Popen
    return _default_context.get_context().Process._Popen(process_obj)
  File "C:\Users\TRIPOLYTA\Anaconda3\lib\multiprocessing\context.py", line 322, in _Popen
    return Popen(process_obj)
  File "C:\Users\TRIPOLYTA\Anaconda3\lib\multiprocessing\popen_spawn_win32.py", line 33, in __init__
    prep_data = spawn.get_preparation_data(process_obj._name)
  File "C:\Users\TRIPOLYTA\Anaconda3\lib\multiprocessing\spawn.py", line 143, in get_preparation_data
    _check_not_importing_main()
  File "C:\Users\TRIPOLYTA\Anaconda3\lib\multiprocessing\spawn.py", line 136, in _check_not_importing_main
    is not going to be frozen to produce an executable.''')
RuntimeError:
        An attempt has been made to start a new process before the
        current process has finished its bootstrapping phase.

        This probably means that you are not using fork to start your
        child processes and you have forgotten to use the proper idiom
        in the main module:

            if __name__ == '__main__':
                freeze_support()
                ...

        The "freeze_support()" line can be omitted if the program
        is not going to be frozen to produce an executable.

Can you help me please?

**Comment by RonnieLiu147** [comment]
> @Cyprusky thank you, but I faced another problem.
> 
> (base) D:\Road.to.Sidang\Python\GaitRecog\Master>python train.py
> C:\Users\TRIPOLYTA\Anaconda3\lib\site-packages\distributed\utils.py:134: RuntimeWarning: Couldn't detect a suitable IP address for reaching '8.8.8.8', defaulting to '127.0.0.1': [WinError 10065] A socket operation was attempted to an unreachable host
> % (host, default, e), RuntimeWarning)
> Initialzing...
> Initializing data source...
> Loading training data...
> Data initialization complete.
> Initializing model...
> Model initialization complete.
> Training START
> Traceback (most recent call last):
> File "train.py", line 21, in 
> m.fit()
> File "D:\Road.to.Sidang\Python\GaitRecog\Master\model\model.py", line 150, in fit
> for seq, view, seq_type, label, batch_frame in train_loader:
> File "C:\Users\TRIPOLYTA\Anaconda3\lib\site-packages\torch\utils\data\dataloader.py", line 819, in **iter**
> return _DataLoaderIter(self)
> File "C:\Users\TRIPOLYTA\Anaconda3\lib\site-packages\torch\utils\data\dataloader.py", line 560, in **init**
> w.start()
> File "C:\Users\TRIPOLYTA\Anaconda3\lib\multiprocessing\process.py", line 105, in start
> self._popen = self._Popen(self)
> File "C:\Users\TRIPOLYTA\Anaconda3\lib\multiprocessing\context.py", line 223, in _Popen
> return _default_context.get_context().Process._Popen(process_obj)
> File "C:\Users\TRIPOLYTA\Anaconda3\lib\multiprocessing\context.py", line 322, in _Popen
> return Popen(process_obj)
> File "C:\Users\TRIPOLYTA\Anaconda3\lib\multiprocessing\popen_spawn_win32.py", line 65, in **init**
> reduction.dump(process_obj, to_child)
> File "C:\Users\TRIPOLYTA\Anaconda3\lib\multiprocessing\reduction.py", line 60, in dump
> ForkingPickler(file, protocol).dump(obj)
> MemoryError
> C:\Users\TRIPOLYTA\Anaconda3\lib\site-packages\distributed\utils.py:134: RuntimeWarning: Couldn't detect a suitable IP address for reaching '8.8.8.8', defaulting to '127.0.0.1': [WinError 10065] A socket operation was attempted to an unreachable host
> % (host, default, e), RuntimeWarning)
> 
> (base) D:\Road.to.Sidang\Python\GaitRecog\Master>Initialzing...
> Initializing data source...
> Loading training data...
> Data initialization complete.
> Initializing model...
> Model initialization complete.
> Training START
> Traceback (most recent call last):
> File "", line 1, in 
> File "C:\Users\TRIPOLYTA\Anaconda3\lib\multiprocessing\spawn.py", line 105, in spawn_main
> exitcode = _main(fd)
> File "C:\Users\TRIPOLYTA\Anaconda3\lib\multiprocessing\spawn.py", line 114, in _main
> prepare(preparation_data)
> File "C:\Users\TRIPOLYTA\Anaconda3\lib\multiprocessing\spawn.py", line 225, in prepare
> _fixup_main_from_path(data['init_main_from_path'])
> File "C:\Users\TRIPOLYTA\Anaconda3\lib\multiprocessing\spawn.py", line 277, in _fixup_main_from_path
> run_name="**mp_main**")
> File "C:\Users\TRIPOLYTA\Anaconda3\lib\runpy.py", line 263, in run_path
> pkg_name=pkg_name, script_name=fname)
> File "C:\Users\TRIPOLYTA\Anaconda3\lib\runpy.py", line 96, in _run_module_code
> mod_name, mod_spec, pkg_name, script_name)
> File "C:\Users\TRIPOLYTA\Anaconda3\lib\runpy.py", line 85, in _run_code
> exec(code, run_globals)
> File "D:\Road.to.Sidang\Python\GaitRecog\Master\train.py", line 21, in 
> m.fit()
> File "D:\Road.to.Sidang\Python\GaitRecog\Master\model\model.py", line 150, in fit
> for seq, view, seq_type, label, batch_frame in train_loader:
> File "C:\Users\TRIPOLYTA\Anaconda3\lib\site-packages\torch\utils\data\dataloader.py", line 819, in **iter**
> return _DataLoaderIter(self)
> File "C:\Users\TRIPOLYTA\Anaconda3\lib\site-packages\torch\utils\data\dataloader.py", line 560, in **init**
> w.start()
> File "C:\Users\TRIPOLYTA\Anaconda3\lib\multiprocessing\process.py", line 105, in start
> self._popen = self._Popen(self)
> File "C:\Users\TRIPOLYTA\Anaconda3\lib\multiprocessing\context.py", line 223, in _Popen
> return _default_context.get_context().Process._Popen(process_obj)
> File "C:\Users\TRIPOLYTA\Anaconda3\lib\multiprocessing\context.py", line 322, in _Popen
> return Popen(process_obj)
> File "C:\Users\TRIPOLYTA\Anaconda3\lib\multiprocessing\popen_spawn_win32.py", line 33, in **init**
> prep_data = spawn.get_preparation_data(process_obj._name)
> File "C:\Users\TRIPOLYTA\Anaconda3\lib\multiprocessing\spawn.py", line 143, in get_preparation_data
> _check_not_importing_main()
> File "C:\Users\TRIPOLYTA\Anaconda3\lib\multiprocessing\spawn.py", line 136, in _check_not_importing_main
> is not going to be frozen to produce an executable.''')
> RuntimeError:
> An attempt has been made to start a new process before the
> current process has finished its bootstrapping phase.
> 
> ```
>     This probably means that you are not using fork to start your
>     child processes and you have forgotten to use the proper idiom
>     in the main module:
> 
>         if __name__ == '__main__':
>             freeze_support()
>             ...
> 
>     The "freeze_support()" line can be omitted if the program
>     is not going to be frozen to produce an executable.
> ```
> Can you help me please?

Hi, I'm facing the same problem that you did. Please let me know what you did if you have made this right.
