### ISSUE TITLE
关于OUMVLP训练时的显存问题？

### ISSUE THREAD

**Issue by mzlx** [AbnerHqC/GaitSet#44]
您好，我现在在OUMVLP数据集上做训练，但是在使用文章中参数时，batch_size为(32, 16)，(C1=C2=64; C3=C4=128; C5=C6=256)，运行报错，说是显存不足。但是我使用了4块16G显卡，请问下，您在做实验时使用了多少块显卡？

**Comment by zztant** [comment]
OUMVLP上batch_size为(32, 16)，至少需要8块1080TI的显存。

**Comment by mzlx** [comment]
> OUMVLP上batch_size为(32, 16)，至少需要8块1080TI的显存。

多谢。我想做一些transfer learning的工作，想用大数据集上训练好的模型，因为目前没有这样的硬件条件，不知道您能不能分享您在OUMVLP上的训练好的model？

**Comment by AbnerHqC** [comment]
您好，抱歉才恢复。最近两天怕是没时间整理，不过您如果还需要的话可以留一下您的邮箱，我可以先单独发给您。

**Comment by mzlx** [comment]
@AbnerHqC 谢谢。我的邮箱是lixiang46@126.com

**Comment by AbnerHqC** [comment]
@mzlx 已发送~

**Comment by mzlx** [comment]
@AbnerHqC 非常感谢您的分享!

**Comment by WhiteDOU** [comment]
您好 请问有没有OUMVLP数据集分享呢
