### ISSUE TITLE
TripletLoss初始化中参数

### ISSUE THREAD

**Issue by Cyprusky** [AbnerHqC/GaitSet#52]
请问init中的hard_or_full这个参数是作何用处呢？还有forward函数里那些dist是代表什么呢？谢谢您

**Comment by AbnerHqC** [comment]
您好，hard和full表示in defence of triplet loss这篇文章里的full和hard两种triplet loss。

**Comment by AbnerHqC** [comment]
triplet loss中dist是pairwise的距离矩阵
