### ISSUE TITLE
Code Problem

### ISSUE THREAD

**Issue by Nocoffeeanymore** [AbnerHqC/GaitSet#53]
非常感谢分享。
有很多问题想要向您请教，期待您的回复。

**Comment by Nocoffeeanymore** [comment]
可以问一下为什么要保存label到.npy文件吗？

**Comment by Nocoffeeanymore** [comment]
可以问一下为什么DataSet里面需要设置index_dict吗？

**Comment by Nocoffeeanymore** [comment]
在生成 seq_dir 时使用了：seq_dir.append([_seq_dir])
具体代码：
`def load_data(dataset_path, resolution, dataset, pid_num, pid_shuffle, cache=True):
    seq_dir = list()
    view = list()
    seq_type = list()
    label = list()

    for _label in sorted(list(os.listdir(dataset_path))):
        # In CASIA-B, data of subject #5 is incomplete.
        # Thus, we ignore it in training.
        if dataset == 'CASIA-B' and _label == '005':
            continue
        label_path = osp.join(dataset_path, _label)
        for _seq_type in sorted(list(os.listdir(label_path))):
            seq_type_path = osp.join(label_path, _seq_type)
            for _view in sorted(list(os.listdir(seq_type_path))):
                _seq_dir = osp.join(seq_type_path, _view)
                seqs = os.listdir(_seq_dir)
                if len(seqs) > 0:
                    seq_dir.append([_seq_dir])
                    label.append(_label)
                    seq_type.append(_seq_type)
                    view.append(_view)`
请问为什么要在_seq_dir变量外面添加[]呢？

在后面的DataSet.__getitem__()函数里面则是：
data = [self.__loader__(_path) for _path in self.seq_dir[index]]
具体代码：
`    def __getitem__(self, index):
        # pose sequence sampling
        if not self.cache:
            data = [self.__loader__(_path) for _path in self.seq_dir[index]]
            frame_set = [set(feature.coords['frame'].values.tolist()) for feature in data]
            frame_set = list(set.intersection(*frame_set))`

每个index对应一个sequence，这样的理解对吗

**Comment by AbnerHqC** [comment]
您好，抱歉没有及时回复。保存pid是因为我们做实验的时候有试过shuffle id之后再分割训练测试集，保存是为了每次使用相同的训练集训练。目前这一功能没用。

**Comment by AbnerHqC** [comment]
index_dict是为了对数据的不同属性建立索引，比如我可以用这个dict很方便的找出所有cl的数据，或者所有18度的数据，或者所有002号人的所有背包的数据里面存的值是对应属性的样本在self.data中的index。

**Comment by AbnerHqC** [comment]
关于最后一个问题。您的理解是对的。代码在写的时候考虑了使用多种特征的需要，比如对每个样本除了轮廓图外还有其他几种特征。这样每个样本实际上会读到一个多种特征组成的sequence。

**Comment by Nocoffeeanymore** [comment]
非常感谢您的回复。
