### ISSUE TITLE
准确率和验证

### ISSUE THREAD

**Issue by Nocoffeeanymore** [AbnerHqC/GaitSet#59]
您的python数据运算用的太6了，结果还可以猜得出是什么，过程全靠蒙。
最近又遇到一些问题需要向您请教：
（1）每个视角的准确率：为什么需要考虑是否包含相同视角呢？
（2）验证集的划分，您的代码是根据seq_tyoe进行划分的，如下：
`    # 注册集
    probe_seq_dict = {'CASIA': [['nm-05', 'nm-06'], ['bg-01', 'bg-02'], ['cl-01', 'cl-02']],
                      'OUMVLP': [['00']]}
    # 验证集
    gallery_seq_dict = {'CASIA': [['nm-01', 'nm-02', 'nm-03', 'nm-04']],
                        'OUMVLP': [['01']]}`
请问为什么要这样划分呢？
（3）关于准确率的计算：取最小距离的seq的label作为预测值；实际运用的时候还有可能查询的并没有注册过，怎么通过feature之间的欧氏距离来判断呢？

**Comment by AbnerHqC** [comment]
过奖了;)
1）因为在其他文章的设定下，cross-view是不含同视角的。（同视角也确实太简单了，nm的情况很容易就都是100%）
2）OUMVLP的划分是数据集规定的，CASIA-B的划分是依照了之前的多数工作的设置，为了对比方便使用了同样的设置。
3）这确实是个问题，目前训练的模型只负责提特征。如果要处理这种gallery中没有prob的开集问题的话还需要其他算法进一步处理。

**Comment by Nocoffeeanymore** [comment]
谢谢

**Comment by Summer-sss** [comment]
> 您的python数据运算用的太6了，结果还可以猜得出是什么，过程全靠蒙。
> 最近又遇到一些问题需要向您请教：
> （1）每个视角的准确率：为什么需要考虑是否包含相同视角呢？
> （2）验证集的划分，您的代码是根据seq_tyoe进行划分的，如下：
> ` # 注册集 probe_seq_dict = {'CASIA': [['nm-05', 'nm-06'], ['bg-01', 'bg-02'], ['cl-01', 'cl-02']], 'OUMVLP': [['00']]} # 验证集 gallery_seq_dict = {'CASIA': [['nm-01', 'nm-02', 'nm-03', 'nm-04']], 'OUMVLP': [['01']]}`
> 请问为什么要这样划分呢？
> （3）关于准确率的计算：取最小距离的seq的label作为预测值；实际运用的时候还有可能查询的并没有注册过，怎么通过feature之间的欧氏距

> 您的python数据运算用的太6了，结果还可以猜得出是什么，过程全靠蒙。
> 最近又遇到一些问题需要向您请教：
> （1）每个视角的准确率：为什么需要考虑是否包含相同视角呢？
> （2）验证集的划分，您的代码是根据seq_tyoe进行划分的，如下：
> ` # 注册集 probe_seq_dict = {'CASIA': [['nm-05', 'nm-06'], ['bg-01', 'bg-02'], ['cl-01', 'cl-02']], 'OUMVLP': [['00']]} # 验证集 gallery_seq_dict = {'CASIA': [['nm-01', 'nm-02', 'nm-03', 'nm-04']], 'OUMVLP': [['01']]}`
> 请问为什么要这样划分呢？
> （3）关于准确率的计算：取最小距离的seq的label作为预测值；实际运用的时候还有可能查询的并没有注册过，怎么通过feature之间的欧氏距离来判断呢？

你好，最近我遇到了有关准确率计算的问题现向你请教，求出dist之后，是如何得出idx的label的呢，感谢你的答复

**Comment by Nocoffeeanymore** [comment]
你好，虽然不知道还能不能对你有任何的帮助。gaitset 仅提取输入序列的特征向量，还需要和其他注册样本（假设你的数据库里已有多个人的的特征向量）分别进行距离的计算，从这些结果中选取相似度最大的——距离的倒数。如果它高于你的阈值，即结果有效，表示在数据库里注册过；如果没有超过阈值，表示并不包含在已经注册的样本里




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "AbnerHqC/GaitSet"                                                                                    <notifications@github.com&gt;;
发送时间:&nbsp;2020年8月14日(星期五) 上午9:49
收件人:&nbsp;"AbnerHqC/GaitSet"<GaitSet@noreply.github.com&gt;;
抄送:&nbsp;"陈柳宏"<2754564669@qq.com&gt;;"Author"<author@noreply.github.com&gt;;
主题:&nbsp;Re: [AbnerHqC/GaitSet] 准确率和验证 (#59)





  
您的python数据运算用的太6了，结果还可以猜得出是什么，过程全靠蒙。
 最近又遇到一些问题需要向您请教：
 （1）每个视角的准确率：为什么需要考虑是否包含相同视角呢？
 （2）验证集的划分，您的代码是根据seq_tyoe进行划分的，如下：
  # 注册集 probe_seq_dict = {'CASIA': [['nm-05', 'nm-06'], ['bg-01', 'bg-02'], ['cl-01', 'cl-02']], 'OUMVLP': [['00']]} # 验证集 gallery_seq_dict = {'CASIA': [['nm-01', 'nm-02', 'nm-03', 'nm-04']], 'OUMVLP': [['01']]}
 请问为什么要这样划分呢？
 （3）关于准确率的计算：取最小距离的seq的label作为预测值；实际运用的时候还有可能查询的并没有注册过，怎么通过feature之间的欧氏距
   
您的python数据运算用的太6了，结果还可以猜得出是什么，过程全靠蒙。
 最近又遇到一些问题需要向您请教：
 （1）每个视角的准确率：为什么需要考虑是否包含相同视角呢？
 （2）验证集的划分，您的代码是根据seq_tyoe进行划分的，如下：
  # 注册集 probe_seq_dict = {'CASIA': [['nm-05', 'nm-06'], ['bg-01', 'bg-02'], ['cl-01', 'cl-02']], 'OUMVLP': [['00']]} # 验证集 gallery_seq_dict = {'CASIA': [['nm-01', 'nm-02', 'nm-03', 'nm-04']], 'OUMVLP': [['01']]}
 请问为什么要这样划分呢？
 （3）关于准确率的计算：取最小距离的seq的label作为预测值；实际运用的时候还有可能查询的并没有注册过，怎么通过feature之间的欧氏距离来判断呢？
  
你好，最近我遇到了有关准确率计算的问题现向你请教，求出dist之后，是如何得出idx的label的呢，感谢你的答复

**Comment by Summer-sss** [comment]
你好，我出现了这样一个问题，我用训练好的模型，选取2个人的训练集，full_loss_num=2,但是正正样本的距离均小于正负样本的距离，为什么识别率不是百分之百呢？ (主要现象:选取74个人作为训练样本时，full_loss_num收敛且趋于0，loss也很低，但是在训练集上的识别率大约只有18%)，非常感谢您的答复------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;&quot;Nocoffeeanymore&quot;<notifications@github.com&gt;
发送时间:&nbsp;2020年8月20日(星期四) 上午10:07
收件人:&nbsp;&quot;AbnerHqC/GaitSet&quot;<GaitSet@noreply.github.com&gt;;
抄送:&nbsp;&quot;Summer-sss&quot;<3197395595@qq.com&gt;;&quot;Comment&quot;<comment@noreply.github.com&gt;;
主题:&nbsp;Re: [AbnerHqC/GaitSet] 准确率和验证 (#59)

**Comment by Nocoffeeanymore** [comment]
不太清楚您的具体情况，仅提供一点小的想法哈~
正正的距离小于正负的距离，说明特征提取没问题。
但是如何判断是否识别了，还是要看具体的计算，可能正正之间的距离还是太大了，没达到阈值，你可以看看他的代码


------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "AbnerHqC/GaitSet"                                                                                    <notifications@github.com&gt;;
发送时间:&nbsp;2020年8月20日(星期四) 上午10:30
收件人:&nbsp;"AbnerHqC/GaitSet"<GaitSet@noreply.github.com&gt;;
抄送:&nbsp;"陈柳宏"<2754564669@qq.com&gt;;"Author"<author@noreply.github.com&gt;;
主题:&nbsp;Re: [AbnerHqC/GaitSet] 准确率和验证 (#59)





 你好，我出现了这样一个问题，我用训练好的模型，选取2个人的训练集，full_loss_num=2,但是正正样本的距离均小于正负样本的距离，为什么识别率不是百分之百呢？ (主要现象:选取74个人作为训练样本时，full_loss_num收敛且趋于0，loss也很低，但是在训练集上的识别率大约只有18%)，非常感谢您的答复------------------&amp;nbsp;原始邮件&amp;nbsp;------------------ 
 发件人:&amp;nbsp;&amp;quot;Nocoffeeanymore&amp;quot;<notifications@github.com&amp;gt; 
 发送时间:&amp;nbsp;2020年8月20日(星期四) 上午10:07 
 收件人:&amp;nbsp;&amp;quot;AbnerHqC/GaitSet&amp;quot;<GaitSet@noreply.github.com&amp;gt;; 
 抄送:&amp;nbsp;&amp;quot;Summer-sss&amp;quot;<3197395595@qq.com&amp;gt;;&amp;quot;Comment&amp;quot;<comment@noreply.github.com&amp;gt;; 
 主题:&amp;nbsp;Re: [AbnerHqC/GaitSet] 准确率和验证 (#59)

**Comment by Summer-sss** [comment]
阈值指的是margin吗



---原始邮件---
发件人: "Nocoffeeanymore"<notifications@github.com&gt;
发送时间: 2020年8月20日(周四) 上午10:37
收件人: "AbnerHqC/GaitSet"<GaitSet@noreply.github.com&gt;;
抄送: "Summer-sss"<3197395595@qq.com&gt;;"Comment"<comment@noreply.github.com&gt;;
主题: Re: [AbnerHqC/GaitSet] 准确率和验证 (#59)




 不太清楚您的具体情况，仅提供一点小的想法哈~ 
 正正的距离小于正负的距离，说明特征提取没问题。 
 但是如何判断是否识别了，还是要看具体的计算，可能正正之间的距离还是太大了，没达到阈值，你可以看看他的代码 
 
 
 ------------------&amp;nbsp;原始邮件&amp;nbsp;------------------ 
 发件人:                                                                                                                        "AbnerHqC/GaitSet"                                                                                    <notifications@github.com&amp;gt;; 
 发送时间:&amp;nbsp;2020年8月20日(星期四) 上午10:30 
 收件人:&amp;nbsp;"AbnerHqC/GaitSet"<GaitSet@noreply.github.com&amp;gt;; 
 抄送:&amp;nbsp;"陈柳宏"<2754564669@qq.com&amp;gt;;"Author"<author@noreply.github.com&amp;gt;; 
 主题:&amp;nbsp;Re: [AbnerHqC/GaitSet] 准确率和验证 (#59) 
 
 
 
 
 
  你好，我出现了这样一个问题，我用训练好的模型，选取2个人的训练集，full_loss_num=2,但是正正样本的距离均小于正负样本的距离，为什么识别率不是百分之百呢？ (主要现象:选取74个人作为训练样本时，full_loss_num收敛且趋于0，loss也很低，但是在训练集上的识别率大约只有18%)，非常感谢您的答复------------------&amp;amp;nbsp;原始邮件&amp;amp;nbsp;------------------  
  发件人:&amp;amp;nbsp;&amp;amp;quot;Nocoffeeanymore&amp;amp;quot;<notifications@github.com&amp;amp;gt;  
  发送时间:&amp;amp;nbsp;2020年8月20日(星期四) 上午10:07  
  收件人:&amp;amp;nbsp;&amp;amp;quot;AbnerHqC/GaitSet&amp;amp;quot;<GaitSet@noreply.github.com&amp;amp;gt;;  
  抄送:&amp;amp;nbsp;&amp;amp;quot;Summer-sss&amp;amp;quot;<3197395595@qq.com&amp;amp;gt;;&amp;amp;quot;Comment&amp;amp;quot;<comment@noreply.github.com&amp;amp;gt;;  
  主题:&amp;amp;nbsp;Re: [AbnerHqC/GaitSet] 准确率和验证 (#59)

**Comment by Nocoffeeanymore** [comment]
时间有点久了，这个太难记得了
你可以看看他是怎么计算准确率的，然后就能知道他是怎么判断是否检测正确的


------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "AbnerHqC/GaitSet"                                                                                    <notifications@github.com&gt;;
发送时间:&nbsp;2020年8月20日(星期四) 上午10:46
收件人:&nbsp;"AbnerHqC/GaitSet"<GaitSet@noreply.github.com&gt;;
抄送:&nbsp;"陈柳宏"<2754564669@qq.com&gt;;"Author"<author@noreply.github.com&gt;;
主题:&nbsp;Re: [AbnerHqC/GaitSet] 准确率和验证 (#59)





 阈值指的是margin吗 
 
 
 
 ---原始邮件--- 
 发件人: "Nocoffeeanymore"<notifications@github.com&amp;gt; 
 发送时间: 2020年8月20日(周四) 上午10:37 
 收件人: "AbnerHqC/GaitSet"<GaitSet@noreply.github.com&amp;gt;; 
 抄送: "Summer-sss"<3197395595@qq.com&amp;gt;;"Comment"<comment@noreply.github.com&amp;gt;; 
 主题: Re: [AbnerHqC/GaitSet] 准确率和验证 (#59) 
 
 
 
 
  不太清楚您的具体情况，仅提供一点小的想法哈~  
  正正的距离小于正负的距离，说明特征提取没问题。  
  但是如何判断是否识别了，还是要看具体的计算，可能正正之间的距离还是太大了，没达到阈值，你可以看看他的代码  
   
   
  ------------------&amp;amp;nbsp;原始邮件&amp;amp;nbsp;------------------  
  发件人:                                                                                                                        "AbnerHqC/GaitSet"                                                                                    <notifications@github.com&amp;amp;gt;;  
  发送时间:&amp;amp;nbsp;2020年8月20日(星期四) 上午10:30  
  收件人:&amp;amp;nbsp;"AbnerHqC/GaitSet"<GaitSet@noreply.github.com&amp;amp;gt;;  
  抄送:&amp;amp;nbsp;"陈柳宏"<2754564669@qq.com&amp;amp;gt;;"Author"<author@noreply.github.com&amp;amp;gt;;  
  主题:&amp;amp;nbsp;Re: [AbnerHqC/GaitSet] 准确率和验证 (#59)  
   
   
   
   
   
   你好，我出现了这样一个问题，我用训练好的模型，选取2个人的训练集，full_loss_num=2,但是正正样本的距离均小于正负样本的距离，为什么识别率不是百分之百呢？ (主要现象:选取74个人作为训练样本时，full_loss_num收敛且趋于0，loss也很低，但是在训练集上的识别率大约只有18%)，非常感谢您的答复------------------&amp;amp;amp;nbsp;原始邮件&amp;amp;amp;nbsp;------------------   
   发件人:&amp;amp;amp;nbsp;&amp;amp;amp;quot;Nocoffeeanymore&amp;amp;amp;quot;<notifications@github.com&amp;amp;amp;gt;   
   发送时间:&amp;amp;amp;nbsp;2020年8月20日(星期四) 上午10:07   
   收件人:&amp;amp;amp;nbsp;&amp;amp;amp;quot;AbnerHqC/GaitSet&amp;amp;amp;quot;<GaitSet@noreply.github.com&amp;amp;amp;gt;;   
   抄送:&amp;amp;amp;nbsp;&amp;amp;amp;quot;Summer-sss&amp;amp;amp;quot;<3197395595@qq.com&amp;amp;amp;gt;;&amp;amp;amp;quot;Comment&amp;amp;amp;quot;<comment@noreply.github.com&amp;amp;amp;gt;;   
   主题:&amp;amp;amp;nbsp;Re: [AbnerHqC/GaitSet] 准确率和验证 (#59)

**Comment by Summer-sss** [comment]
好的👌，谢谢------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;&quot;Nocoffeeanymore&quot;<notifications@github.com&gt;
发送时间:&nbsp;2020年8月20日(星期四) 上午10:48
收件人:&nbsp;&quot;AbnerHqC/GaitSet&quot;<GaitSet@noreply.github.com&gt;;
抄送:&nbsp;&quot;Summer-sss&quot;<3197395595@qq.com&gt;;&quot;Comment&quot;<comment@noreply.github.com&gt;;
主题:&nbsp;Re: [AbnerHqC/GaitSet] 准确率和验证 (#59)

**Comment by Nocoffeeanymore** [comment]
不客气~




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "AbnerHqC/GaitSet"                                                                                    <notifications@github.com&gt;;
发送时间:&nbsp;2020年8月20日(星期四) 上午10:49
收件人:&nbsp;"AbnerHqC/GaitSet"<GaitSet@noreply.github.com&gt;;
抄送:&nbsp;"陈柳宏"<2754564669@qq.com&gt;;"Author"<author@noreply.github.com&gt;;
主题:&nbsp;Re: [AbnerHqC/GaitSet] 准确率和验证 (#59)





 好的👌，谢谢------------------&amp;nbsp;原始邮件&amp;nbsp;------------------ 
 发件人:&amp;nbsp;&amp;quot;Nocoffeeanymore&amp;quot;<notifications@github.com&amp;gt; 
 发送时间:&amp;nbsp;2020年8月20日(星期四) 上午10:48 
 收件人:&amp;nbsp;&amp;quot;AbnerHqC/GaitSet&amp;quot;<GaitSet@noreply.github.com&amp;gt;; 
 抄送:&amp;nbsp;&amp;quot;Summer-sss&amp;quot;<3197395595@qq.com&amp;gt;;&amp;quot;Comment&amp;quot;<comment@noreply.github.com&amp;gt;; 
 主题:&amp;nbsp;Re: [AbnerHqC/GaitSet] 准确率和验证 (#59)

**Comment by Summer-sss** [comment]
识别率的计算，是用probe的特征向量求与gallery的特征向量的dist,然后取最小的dist的label作为预测值，会有哪里阈值吗



---原始邮件---
发件人: "Nocoffeeanymore"<notifications@github.com&gt;
发送时间: 2020年8月20日(周四) 上午10:51
收件人: "AbnerHqC/GaitSet"<GaitSet@noreply.github.com&gt;;
抄送: "Summer-sss"<3197395595@qq.com&gt;;"Comment"<comment@noreply.github.com&gt;;
主题: Re: [AbnerHqC/GaitSet] 准确率和验证 (#59)




 不客气~ 
 
 
 
 
 ------------------&amp;nbsp;原始邮件&amp;nbsp;------------------ 
 发件人:                                                                                                                        "AbnerHqC/GaitSet"                                                                                    <notifications@github.com&amp;gt;; 
 发送时间:&amp;nbsp;2020年8月20日(星期四) 上午10:49 
 收件人:&amp;nbsp;"AbnerHqC/GaitSet"<GaitSet@noreply.github.com&amp;gt;; 
 抄送:&amp;nbsp;"陈柳宏"<2754564669@qq.com&amp;gt;;"Author"<author@noreply.github.com&amp;gt;; 
 主题:&amp;nbsp;Re: [AbnerHqC/GaitSet] 准确率和验证 (#59) 
 
 
 
 
 
  好的👌，谢谢------------------&amp;amp;nbsp;原始邮件&amp;amp;nbsp;------------------  
  发件人:&amp;amp;nbsp;&amp;amp;quot;Nocoffeeanymore&amp;amp;quot;<notifications@github.com&amp;amp;gt;  
  发送时间:&amp;amp;nbsp;2020年8月20日(星期四) 上午10:48  
  收件人:&amp;amp;nbsp;&amp;amp;quot;AbnerHqC/GaitSet&amp;amp;quot;<GaitSet@noreply.github.com&amp;amp;gt;;  
  抄送:&amp;amp;nbsp;&amp;amp;quot;Summer-sss&amp;amp;quot;<3197395595@qq.com&amp;amp;gt;;&amp;amp;quot;Comment&amp;amp;quot;<comment@noreply.github.com&amp;amp;gt;;  
  主题:&amp;amp;nbsp;Re: [AbnerHqC/GaitSet] 准确率和验证 (#59)

**Comment by Nocoffeeanymore** [comment]
那是我想多了
print一下调用训练好的模型的inference结果看看

**Comment by Summer-sss** [comment]
嗯嗯，谢谢------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;&quot;Nocoffeeanymore&quot;<notifications@github.com&gt;
发送时间:&nbsp;2020年8月20日(星期四) 中午11:03
收件人:&nbsp;&quot;AbnerHqC/GaitSet&quot;<GaitSet@noreply.github.com&gt;;
抄送:&nbsp;&quot;Summer-sss&quot;<3197395595@qq.com&gt;;&quot;Comment&quot;<comment@noreply.github.com&gt;;
主题:&nbsp;Re: [AbnerHqC/GaitSet] 准确率和验证 (#59)
