### ISSUE TITLE
Prepocess

### ISSUE THREAD

**Issue by xiangdeyizhang** [AbnerHqC/GaitSet#6]
你好，AbnerHqcz！
      我想咨询下，这个训练文件夹GaitDataSet中s的图片是不是都要归一化到88*128的尺寸呢？并且归一化的方法中提高了滑动均值滤波，这个滑动帧数是30帧吗？那最后的三十帧怎么滑动呢？是循环滑动均值吗？

谢谢，期待你的回复

**Comment by AbnerHqC** [comment]
我们输入的尺寸是64*64，就是先切一个方框，然后resize到64*64。不是88*128。然后滑动滤波的话主要应该是增加稳定性，这个我们没有做，应该是做一个指数移动平均之类的操作。你可以加进去试一下。

**Comment by AbnerHqC** [comment]
不好意思，公开数据集有相关协议的，我们不能以任何方式redistribute。预处理遇到的问题欢迎大家提问和解答。

**Comment by as472780551** [comment]
好的，谢谢。

**Comment by AbnerHqC** [comment]
鉴于大家问预处理的问题比较多，近期将提交我们预处理的代码
