### ISSUE TITLE
Not getting the accuracy as promised

### ISSUE THREAD

**Issue by Purav-Zumkhawala** [AbnerHqC/GaitSet#61]
Hi,

I have trained using the CASIA-B dataset till 80000 iterations and am not getting accuracy as described in the code and readme. I do not know what I am doing wrong. 

I have also tried testing with the weights given in the work directory. But I can not get the result shown by you. Any suggestions ?

I get the result as shown in the image.

![Screenshot from 2019-04-26 15-38-34](https://user-images.githubusercontent.com/36352057/56808486-3f95d580-684f-11e9-929e-d7370010e715.png)

**Comment by Purav-Zumkhawala** [comment]
Never Mind I got it.

**Comment by Summer-sss** [comment]
> I have trained using the CASIA-B dataset till 80000 iterations and am not getting accuracy as described in the code and readme. I do not know what I am doing wrong.
> 
> I have also tried testing with the weights given in the work directory. But I can not get the result shown by you. Any suggestions ?
> 
> I get the result as shown in the image.

Hello，I also met a similar problem. How did you solve it? Thank you for your reply.
